import type { Metadata } from "next";

import { Kdam_Thmor_Pro } from 'next/font/google';
import "./globals.css";

const kdamThmorPro = Kdam_Thmor_Pro({
  subsets: ['latin'],
  variable: '--font-kdam-thmor-pro',
  weight: '400',
  display: 'swap'
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${kdamThmorPro.variable} scroll-smooth`} >
      <body className="bg-white h-full w-full min-h-screen flex flex-col">
        <div className="flex flex-col flex-nowrap w-full m-auto p-0">
            {children}
          </div>
        </body>
    </html>
  );
}
